# Sample API requests for testing

@port = 3111

OPTIONS  http://localhost:{{port}}

### Get all databases
GET http://localhost:{{port}}/api/databases
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0X3VzZXJAZXhhbXBsZS5jb20iLCJleHAiOjIwNjE1MDkyMDV9.6QRUaU0gjAhaqWdmZyq5lm9lXVTh6aspFPN-SCF_X6M


### Get all tables for a database
GET http://localhost:{{port}}/api/databases/users/tables
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0X3VzZXJAZXhhbXBsZS5jb20iLCJleHAiOjIwNjE1MDkyMDV9.6QRUaU0gjAhaqWdmZyq5lm9lXVTh6aspFPN-SCF_X6M


### Get table schema
GET http://localhost:{{port}}/api/databases/users/tables/public.repositories/schema
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0X3VzZXJAZXhhbXBsZS5jb20iLCJleHAiOjIwNjE1MDkyMDV9.6QRUaU0gjAhaqWdmZyq5lm9lXVTh6aspFPN-SCF_X6M

### Get full schema
GET http://localhost:{{port}}/api/schema
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0X3VzZXJAZXhhbXBsZS5jb20iLCJleHAiOjIwNjE1MDkyMDV9.6QRUaU0gjAhaqWdmZyq5lm9lXVTh6aspFPN-SCF_X6M


### Execute query
POST http://localhost:{{port}}/api/execute-query
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0X3VzZXJAZXhhbXBsZS5jb20iLCJleHAiOjIwNjE1MDkyMDV9.6QRUaU0gjAhaqWdmZyq5lm9lXVTh6aspFPN-SCF_X6M
Content-Type: application/json

{
  "db_name": "employees",
  "query": "select * from employees.salary"
}
